<?php

namespace Database\Seeders;

use App\Models\BusinessLock;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class BusinessLockSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $regions = [
            ['name' => 'Agra'],
            ['name' => 'Ahmedabad'],
            ['name' => 'Ahmednagar'],
            ['name' => 'Ajmer'],
            ['name' => 'Alappuzha'],
            ['name' => 'Aligarh'],
            ['name' => 'Allahabad'],
            ['name' => 'Alleppey'],
            ['name' => 'Ambala'],
            ['name' => 'Amritsar'],
            ['name' => 'Anand'],
            ['name' => 'Anantnag'],
            ['name' => 'Aurangabad'],
            ['name' => 'Banglore'],
            ['name' => 'Banglore1'],
            ['name' => 'Baramulla'],
            ['name' => 'Bareilly'],
            ['name' => 'Baroda'],
            ['name' => 'Baroda1'],
            ['name' => 'Beed'],
            ['name' => 'Belgaum'],
            ['name' => 'Bellary'],
            ['name' => 'Betul'],
            ['name' => 'Bharuch'],
            ['name' => 'Bhatinda'],
            ['name' => 'Bhavnagar'],
            ['name' => 'Bhilai'],
            ['name' => 'Bhiwadi'],
            ['name' => 'Bhopal'],
            ['name' => 'Bhubaneshwar'],
            ['name' => 'Bijapur'],
            ['name' => 'Bilaspur'],
            ['name' => 'Calicut'],
            ['name' => 'Chandigarh'],
            ['name' => 'Chennai'],
            ['name' => 'Chindwara'],
            ['name' => 'Chiplun'],
            ['name' => 'Chitradurga'],
            ['name' => 'Cochin'],
            ['name' => 'Coimbatore'],
            ['name' => 'Cuttack'],
            ['name' => 'Davanagere'],
            ['name' => 'Dehradun'],
            ['name' => 'Delhi'],
            ['name' => 'Delhi2'],
            ['name' => 'Dhanbad'],
            ['name' => 'Dharward'],
            ['name' => 'Dispur -Assam'],
            ['name' => 'Durg'],
            ['name' => 'Ernakulam'],
            ['name' => 'Erode'],
            ['name' => 'Faizabad'],
            ['name' => 'Faridabad'],
            ['name' => 'Gandhidham'],
            ['name' => 'Gandhinagar'],
            ['name' => 'Goa'],
            ['name' => 'Godhra'],
            ['name' => 'Gorakhpur'],
            ['name' => 'Gulbargha'],
            ['name' => 'Gurgaon'],
            ['name' => 'Gurugram'],
            ['name' => 'Guwahati'],
            ['name' => 'Gwalior'],
            ['name' => 'Haldwani'],
            ['name' => 'Himatnagar'],
            ['name' => 'Hisar'],
            ['name' => 'Hoshiarpur'],
            ['name' => 'Howrah'],
            ['name' => 'Hubli'],
            ['name' => 'Hyderabad'],
            ['name' => 'Indore'],
            ['name' => 'Jabalpur'],
            ['name' => 'Jaipur'],
            ['name' => 'Jalandhar'],
            ['name' => 'Jalgaon'],
            ['name' => 'Jammu'],
            ['name' => 'Jamnagar'],
            ['name' => 'Jamshedpur'],
            ['name' => 'Jhansi'],
            ['name' => 'Junagadh'],
            ['name' => 'Kanchipuram'],
            ['name' => 'Kannur'],
            ['name' => 'Kanpur'],
            ['name' => 'Karad'],
            ['name' => 'Karnal'],
            ['name' => 'Khandwa'],
            ['name' => 'Kolhapur'],
            ['name' => 'Kolkata'],
            ['name' => 'Koppal'],
            ['name' => 'Korba'],
            ['name' => 'Kota'],
            ['name' => 'Kottyam'],
            ['name' => 'Latur'],
            ['name' => 'Lucknow'],
            ['name' => 'Ludhiana'],
            ['name' => 'Madhurai'],
            ['name' => 'Madurai'],
            ['name' => 'Mahim'],
            ['name' => 'Malappuram'],
            ['name' => 'Malapur'],
            ['name' => 'Malegaon'],
            ['name' => 'Mandi'],
            ['name' => 'Mangalore'],
            ['name' => 'Manimajra'],
            ['name' => 'Mansa'],
            ['name' => 'Mathura'],
            ['name' => 'Medak'],
            ['name' => 'Meerut'],
            ['name' => 'Mehsana'],
            ['name' => 'Miraj'],
            ['name' => 'Mohali'],
            ['name' => 'Mumbai'],
            ['name' => 'Mumbai2'],
            ['name' => 'Mumbai3'],
            ['name' => 'Muzaffarnagar'],
            ['name' => 'Mysore'],
            ['name' => 'Nagpur'],
            ['name' => 'Nalgonda Telangana'],
            ['name' => 'Nanded'],
            ['name' => 'Nasik'],
            ['name' => 'Noida'],
            ['name' => 'Palakkad'],
            ['name' => 'Palanpur'],
            ['name' => 'Panchkula'],
            ['name' => 'Panipat'],
            ['name' => 'Panjim'],
            ['name' => 'Patiala'],
            ['name' => 'Patna'],
            ['name' => 'Petlad'],
            ['name' => 'Pitampura'],
            ['name' => 'Pondicherry'],
            ['name' => 'Pune'],
            ['name' => 'Raigarh'],
            ['name' => 'Raipur'],
            ['name' => 'Rajahmundry'],
            ['name' => 'Rajkot'],
            ['name' => 'Rajkot1'],
            ['name' => 'Rajmandi'],
            ['name' => 'Ranchi'],
            ['name' => 'Ratlam'],
            ['name' => 'Ratnagiri'],
            ['name' => 'Rohtak'],
            ['name' => 'Salem'],
            ['name' => 'Sambalpur'],
            ['name' => 'Sangli'],
            ['name' => 'Sangpur'],
            ['name' => 'Satara'],
            ['name' => 'Satna'],
            ['name' => 'Secundrabad'],
            ['name' => 'Shimla'],
            ['name' => 'Siliguri'],
            ['name' => 'Sindhudurg'],
            ['name' => 'Solan'],
            ['name' => 'Solapur'],
            ['name' => 'Sonepat'],
            ['name' => 'Srinagar'],
            ['name' => 'Sundargarh'],
            ['name' => 'Surat'],
            ['name' => 'Surat1'],
            ['name' => 'Surendranagar'],
            ['name' => 'Tarnataran'],
            ['name' => 'Thane'],
            ['name' => 'Thanjavur'],
            ['name' => 'Thiruvananthapuram'],
            ['name' => 'Thrissur'],
            ['name' => 'Tirunelveli'],
            ['name' => 'Tirupathi'],
            ['name' => 'Trichy'],
            ['name' => 'Trivandrum'],
            ['name' => 'Udaipur'],
            ['name' => 'Udupi'],
            ['name' => 'Ujjain'],
            ['name' => 'Valsad'],
            ['name' => 'Vapi'],
            ['name' => 'Varanasi'],
            ['name' => 'Vellore'],
            ['name' => 'Vijaywada'],
            ['name' => 'Vishakhapatnam'],
            ['name' => 'Yamunanagar'],
        ];

        foreach ($regions as $region) {
            BusinessLock::firstOrCreate(
                ['name' => $region['name']],
                ['is_active' => true],
            );
        }
    }
}
