<?php

namespace Database\Seeders;

use App\Models\BusinessLock;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class BusinessLockSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $regions = [
            ['name' => 'AGRA'],
            ['name' => 'AHMEDABAD'],
            ['name' => 'AHMEDNAGAR'],
            ['name' => 'AJMER'],
            ['name' => 'ALAPPUZHA'],
            ['name' => 'ALIGARH'],
            ['name' => 'ALLAHABAD'],
            ['name' => 'ALLEPPEY'],
            ['name' => 'AMBALA'],
            ['name' => 'AMRITSAR'],
            ['name' => 'ANAND'],
            ['name' => 'ANANTNAG'],
            ['name' => 'AURANGABAD'],
            ['name' => 'BANGLORE'],
            ['name' => 'BANGLORE1'],
            ['name' => 'BARAMULLA'],
            ['name' => 'BAREILLY'],
            ['name' => 'BARODA'],
            ['name' => 'BARODA1'],
            ['name' => 'BEED'],
            ['name' => 'BELGAUM'],
            ['name' => 'BELLARY'],
            ['name' => 'BETUL'],
            ['name' => 'BHARUCH'],
            ['name' => 'BHATINDA'],
            ['name' => 'BHAVNAGAR'],
            ['name' => 'BHILAI'],
            ['name' => 'BHIWADI'],
            ['name' => 'BHOPAL'],
            ['name' => 'BHUBANESHWAR'],
            ['name' => 'BIJAPUR'],
            ['name' => 'BILASPUR'],
            ['name' => 'CALICUT'],
            ['name' => 'CHANDIGARH'],
            ['name' => 'CHENNAI'],
            ['name' => 'CHINDWARA'],
            ['name' => 'CHIPLUN'],
            ['name' => 'CHITRADURGA'],
            ['name' => 'COCHIN'],
            ['name' => 'COIMBATORE'],
            ['name' => 'CUTTACK'],
            ['name' => 'DAVANAGERE'],
            ['name' => 'DEHRADUN'],
            ['name' => 'DELHI'],
            ['name' => 'DELHI2'],
            ['name' => 'DHANBAD'],
            ['name' => 'DHARWARD'],
            ['name' => 'DISPUR -ASSAM'],
            ['name' => 'DURG'],
            ['name' => 'ERNAKULAM'],
            ['name' => 'ERODE'],
            ['name' => 'FAIZABAD'],
            ['name' => 'FARIDABAD'],
            ['name' => 'GANDHIDHAM'],
            ['name' => 'GANDHINAGAR'],
            ['name' => 'GOA'],
            ['name' => 'GODHRA'],
            ['name' => 'GORAKHPUR'],
            ['name' => 'GULBARGHA'],
            ['name' => 'GURGAON'],
            ['name' => 'GURUGRAM'],
            ['name' => 'GUWAHATI'],
            ['name' => 'GWALIOR'],
            ['name' => 'HALDWANI'],
            ['name' => 'HIMATNAGAR'],
            ['name' => 'HISAR'],
            ['name' => 'HOSHIARPUR'],
            ['name' => 'HOWRAH'],
            ['name' => 'HUBLI'],
            ['name' => 'HYDERABAD'],
            ['name' => 'INDORE'],
            ['name' => 'JABALPUR'],
            ['name' => 'JAIPUR'],
            ['name' => 'JALANDHAR'],
            ['name' => 'JALGAON'],
            ['name' => 'JAMMU'],
            ['name' => 'JAMNAGAR'],
            ['name' => 'JAMSHEDPUR'],
            ['name' => 'JHANSI'],
            ['name' => 'JUNAGADH'],
            ['name' => 'KANCHIPURAM'],
            ['name' => 'KANNUR'],
            ['name' => 'KANPUR'],
            ['name' => 'KARAD'],
            ['name' => 'KARNAL'],
            ['name' => 'KHANDWA'],
            ['name' => 'KOLHAPUR'],
            ['name' => 'KOLKATA'],
            ['name' => 'KOPPAL'],
            ['name' => 'KORBA'],
            ['name' => 'KOTA'],
            ['name' => 'KOTTYAM'],
            ['name' => 'LATUR'],
            ['name' => 'LUCKNOW'],
            ['name' => 'LUDHIANA'],
            ['name' => 'MADHURAI'],
            ['name' => 'MADURAI'],
            ['name' => 'MAHIM'],
            ['name' => 'MALAPPURAM'],
            ['name' => 'MALAPUR'],
            ['name' => 'MALEGAON'],
            ['name' => 'MANDI'],
            ['name' => 'MANGALORE'],
            ['name' => 'Manimajra'],
            ['name' => 'MANSA'],
            ['name' => 'MATHURA'],
            ['name' => 'MEDAK'],
            ['name' => 'MEERUT'],
            ['name' => 'MEHSANA'],
            ['name' => 'MIRAJ'],
            ['name' => 'MOHALI'],
            ['name' => 'MUMBAI'],
            ['name' => 'MUMBAI2'],
            ['name' => 'MUMBAI3'],
            ['name' => 'MUZAFFARNAGAR'],
            ['name' => 'MYSORE'],
            ['name' => 'NAGPUR'],
            ['name' => 'NALGONDA TELANGANA'],
            ['name' => 'NANDED'],
            ['name' => 'NASIK'],
            ['name' => 'NOIDA'],
            ['name' => 'PALAKKAD'],
            ['name' => 'PALANPUR'],
            ['name' => 'PANCHKULA'],
            ['name' => 'PANIPAT'],
            ['name' => 'PANJIM'],
            ['name' => 'PATIALA'],
            ['name' => 'PATNA'],
            ['name' => 'PETLAD'],
            ['name' => 'PITAMPURA'],
            ['name' => 'PONDICHERRY'],
            ['name' => 'PUNE'],
            ['name' => 'RAIGARH'],
            ['name' => 'RAIPUR'],
            ['name' => 'RAJAHMUNDRY'],
            ['name' => 'RAJKOT'],
            ['name' => 'RAJKOT1'],
            ['name' => 'RAJMANDI'],
            ['name' => 'RANCHI'],
            ['name' => 'RATLAM'],
            ['name' => 'RATNAGIRI'],
            ['name' => 'ROHTAK'],
            ['name' => 'SALEM'],
            ['name' => 'SAMBALPUR'],
            ['name' => 'SANGLI'],
            ['name' => 'SANGPUR'],
            ['name' => 'SATARA'],
            ['name' => 'SATNA'],
            ['name' => 'SECUNDRABAD'],
            ['name' => 'SHIMLA'],
            ['name' => 'SILIGURI'],
            ['name' => 'SINDHUDURG'],
            ['name' => 'SOLAN'],
            ['name' => 'SOLAPUR'],
            ['name' => 'SONEPAT'],
            ['name' => 'SRINAGAR'],
            ['name' => 'SUNDARGARH'],
            ['name' => 'SURAT'],
            ['name' => 'SURAT1'],
            ['name' => 'SURENDRANAGAR'],
            ['name' => 'TARNATARAN'],
            ['name' => 'THANE'],
            ['name' => 'THANJAVUR'],
            ['name' => 'THIRUVANANTHAPURAM'],
            ['name' => 'THRISSUR'],
            ['name' => 'TIRUNELVELI'],
            ['name' => 'TIRUPATHI'],
            ['name' => 'TRICHY'],
            ['name' => 'TRIVANDRUM'],
            ['name' => 'UDAIPUR'],
            ['name' => 'UDUPI'],
            ['name' => 'UJJAIN'],
            ['name' => 'VALSAD'],
            ['name' => 'VAPI'],
            ['name' => 'VARANASI'],
            ['name' => 'VELLORE'],
            ['name' => 'VIJAYWADA'],
            ['name' => 'vishakhapatnam'],
            ['name' => 'YAMUNANAGAR'],
        ];

        foreach ($regions as $region) {
            BusinessLock::firstOrCreate(
                ['name' => $region['name']],
                ['is_active' => true],
            );
        }
    }
}
