<?php

namespace Database\Seeders;

use App\Models\Make;
use Illuminate\Database\Seeder;

class MakeSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        //
        $makes = [
            ['product_id' => 1, 'name' => " HARVESTER"],
            ['product_id' => 1, 'name' => "3 S INDUSTRIES"],
            ['product_id' => 1, 'name' => "3EV INDUSTRIES PVT LTD"],
            ['product_id' => 1, 'name' => "A K GUPTA AND CO"],
            ['product_id' => 1, 'name' => "A V AUTOMOTIVES PVT LTD"],
            ['product_id' => 1, 'name' => "AADHYA ENTERPRISES"],
            ['product_id' => 1, 'name' => "AAHANA COMMERCE PVT LTD"],
            ['product_id' => 1, 'name' => "AB EXCAVATOR"],
            ['product_id' => 1, 'name' => "ACCRETION POWER AUTOS"],
            ['product_id' => 1, 'name' => "ACCURA"],
            ['product_id' => 1, 'name' => "ACE"],
            ['product_id' => 1, 'name' => "ACTION EQUIPMENT"],
            ['product_id' => 1, 'name' => "ADHIRAJ AUTOMOBILES"],
            ['product_id' => 1, 'name' => "AFZAL ENGINEERING"],
            ['product_id' => 1, 'name' => "AGRI KING"],
            ['product_id' => 1, 'name' => "AJAX"],
            ['product_id' => 1, 'name' => "AJOX FIORI"],
            ['product_id' => 1, 'name' => "AK AUTO ELECTRIC"],
            ['product_id' => 1, 'name' => "AK GUPTA AND CO"],
            ['product_id' => 1, 'name' => "AKG EV INTERNATIONAL"],
            ['product_id' => 1, 'name' => "ALLFINE INDUSTRIES"],
            ['product_id' => 1, 'name' => "ALLWYN"],
            ['product_id' => 1, 'name' => "ALTIER ELECTRIC VEHICLES"],
            ['product_id' => 1, 'name' => "ALTIGREEN"],
            ['product_id' => 1, 'name' => "AMBICA STEEL WORKS"],
            ['product_id' => 1, 'name' => "AMBIKA INDUSTRIES"],
            ['product_id' => 1, 'name' => "AMMANN"],
            ['product_id' => 1, 'name' => "AMW"],
            ['product_id' => 1, 'name' => "ANGAD"],
            ['product_id' => 1, 'name' => "ANISH POWERTECH PVT LTD"],
            ['product_id' => 1, 'name' => "ANJALI AUTO"],
            ['product_id' => 1, 'name' => "ANKUSH AUTO"],
            ['product_id' => 1, 'name' => "A-ONE"],
            ['product_id' => 1, 'name' => "APARNA INDUSTRIES"],
            ['product_id' => 1, 'name' => "API"],
            ['product_id' => 1, 'name' => "APOLLO"],
            ['product_id' => 1, 'name' => "APSARA"],
            ['product_id' => 1, 'name' => "AR MOTORS"],
            ['product_id' => 1, 'name' => "ARCANA"],
            ['product_id' => 1, 'name' => "ARCHIT ENTERPRISES"],
            ['product_id' => 1, 'name' => "ARIEL"],
            ['product_id' => 1, 'name' => "ARJUN"],
            ['product_id' => 1, 'name' => "ARMAN GREEN VEHICLE PVT LTD"],
            ['product_id' => 1, 'name' => "ARNA ELECTRIC AUTO PVT LTD"],
            ['product_id' => 1, 'name' => "ARZOO E VEHICLES"],
            ['product_id' => 1, 'name' => "ASH"],
            ['product_id' => 1, 'name' => "ASHMA MOTORS PVT LTD"],
            ['product_id' => 1, 'name' => "ASHOK LEYLAND"],
            ['product_id' => 1, 'name' => "ASHVA SHAKTI"],
            ['product_id' => 1, 'name' => "ASIA MOTOR WORKS LTD"],
            ['product_id' => 1, 'name' => "ASTON MARTIN"],
            ['product_id' => 1, 'name' => "ATLAS"],
            ['product_id' => 1, 'name' => "ATUL"],
            ['product_id' => 1, 'name' => "ATUT SANGAM"],
            ['product_id' => 1, 'name' => "ATV"],
            ['product_id' => 1, 'name' => "AUDI"],
            ['product_id' => 1, 'name' => "AUM ENGINEERS"],
            ['product_id' => 1, 'name' => "AUTOLITE"],
            ['product_id' => 1, 'name' => "AVL Electric Vehicles"],
            ['product_id' => 1, 'name' => "AVON"],
            ['product_id' => 1, 'name' => "AWACHAT INDUSTRIES LTD"],
            ['product_id' => 1, 'name' => "BADSHAH"],
            ['product_id' => 1, 'name' => "BAJAJ"],
            ['product_id' => 1, 'name' => "BANSURI AUTO"],
            ['product_id' => 1, 'name' => "BATRICK AUTO"],
            ['product_id' => 1, 'name' => "BAXY"],
            ['product_id' => 1, 'name' => "BEML"],
            ['product_id' => 1, 'name' => "BENTINCK"],
            ['product_id' => 1, 'name' => "BENTLEY"],
            ['product_id' => 1, 'name' => "BESTWAY"],
            ['product_id' => 1, 'name' => "BHARAT"],
            ['product_id' => 1, 'name' => "BHARAT-BENZ"],
            ['product_id' => 1, 'name' => "BHAVE ELECTRIC VEHICLS PVT LTD"],
            ['product_id' => 1, 'name' => "BHM INDUSTRIES"],
            ['product_id' => 1, 'name' => "BIG BULL TRADER PVT LTD"],
            ['product_id' => 1, 'name' => "BLESS"],
            ['product_id' => 1, 'name' => "BLUE ENERGY"],
            ['product_id' => 1, 'name' => "BMW"],
            ['product_id' => 1, 'name' => "BOBCAT"],
            ['product_id' => 1, 'name' => "BRIGHT AUTO"],
            ['product_id' => 1, 'name' => "BUGATTI"],
            ['product_id' => 1, 'name' => "BUICK"],
            ['product_id' => 1, 'name' => "BULL"],
            ['product_id' => 1, 'name' => "BULLDOZER"],
            ['product_id' => 1, 'name' => "BUS"],
            ['product_id' => 1, 'name' => "BYD"],
            ['product_id' => 1, 'name' => "CADILLAC"],
            ['product_id' => 1, 'name' => "CAPARO AUTOTECH"],
            ['product_id' => 1, 'name' => "CAPITAL AUTO"],
            ['product_id' => 1, 'name' => "CAPTAIN TRACTORS PVT LTD"],
            ['product_id' => 1, 'name' => "CARGO KING"],
            ['product_id' => 1, 'name' => "CARGOTEC INDIA PVT LTD"],
            ['product_id' => 1, 'name' => "CART INDIA"],
            ['product_id' => 1, 'name' => "CASE"],
            ['product_id' => 1, 'name' => "CATERPILLAR"],
            ['product_id' => 1, 'name' => "CEEON"],
            ['product_id' => 1, 'name' => "CEL"],
            ['product_id' => 1, 'name' => "CELLETRON MOTOR WORKS"],
            ['product_id' => 1, 'name' => "CHAMPION"],
            ['product_id' => 1, 'name' => "CHAUHAN AUTO INDUSTRIES"],
            ['product_id' => 1, 'name' => "CHETAK BATTERIES"],
            ['product_id' => 1, 'name' => "CHEVROLET"],
            ['product_id' => 1, 'name' => "CHRYSLER"],
            ['product_id' => 1, 'name' => "CITROEN"],
            ['product_id' => 1, 'name' => "CITY METRO"],
            ['product_id' => 1, 'name' => "CITY SHINE"],
            ['product_id' => 1, 'name' => "CITYGREEN AUTO"],
            ['product_id' => 1, 'name' => "CITYLIFE ELECTRIC"],
            ['product_id' => 1, 'name' => "CLASS"],
            ['product_id' => 1, 'name' => "CLUB CAR"],
            ['product_id' => 1, 'name' => "CNH INDUSTRIAL INDIA PVT LTD"],
            ['product_id' => 1, 'name' => "CONTINENTAL ENGINES PVT LTD"],
            ['product_id' => 1, 'name' => "Crane Kraft India Private Limited"],
            ['product_id' => 1, 'name' => "DABANG"],
            ['product_id' => 1, 'name' => "DAEWOO"],
            ['product_id' => 1, 'name' => "DAKSH INDUSTRIES"],
            ['product_id' => 1, 'name' => "Dasmesh"],
            ['product_id' => 1, 'name' => "DATSUN"],
            ['product_id' => 1, 'name' => "DAVE EXIM"],
            ['product_id' => 1, 'name' => "DC"],
            ['product_id' => 1, 'name' => "DE EUSI MOTORS PVT LTD"],
            ['product_id' => 1, 'name' => "DELTA AUTOCORP"],
            ['product_id' => 1, 'name' => "DELTIC"],
            ['product_id' => 1, 'name' => "DEMAG"],
            ['product_id' => 1, 'name' => "DEUTZ FAHR"],
            ['product_id' => 1, 'name' => "DIAMOND"],
            ['product_id' => 1, 'name' => "DILLI ELECTRIC AUTO PVT LTD"],
            ['product_id' => 1, 'name' => "DIVYA ENTERPRISES"],
            ['product_id' => 1, 'name' => "DMIX SPEEDCRAFTS"],
            ['product_id' => 1, 'name' => "DODGE"],
            ['product_id' => 1, 'name' => "DOOSAN"],
            ['product_id' => 1, 'name' => "DS INDUSTRIES"],
            ['product_id' => 1, 'name' => "DTRMX"],
            ['product_id' => 1, 'name' => "DUKE AUTO"],
            ['product_id' => 1, 'name' => "E FILL ELECTRIC"],
            ['product_id' => 1, 'name' => "E MOTION AUTOMOTIVE INDUSTRY"],
            ['product_id' => 1, 'name' => "EDMRC"],
            ['product_id' => 1, 'name' => "EICHER"],
            ['product_id' => 1, 'name' => "EICHER MOTORS"],
            ['product_id' => 1, 'name' => "EKO"],
            ['product_id' => 1, 'name' => "ELEPHANTA"],
            ['product_id' => 1, 'name' => "ELITE AUTO ENGINEERS"],
            ['product_id' => 1, 'name' => "ELSA CONCRETE MIXER"],
            ['product_id' => 1, 'name' => "ENERGY ELECTRIC VEHICLES"],
            ['product_id' => 1, 'name' => "ENTICE IMPEX"],
            ['product_id' => 1, 'name' => "EPOWER VEHICLES PVT LTD"],
            ['product_id' => 1, 'name' => "ERISHA"],
            ['product_id' => 1, 'name' => "ESCORTS"],
            ['product_id' => 1, 'name' => "ETRIO"],
            ['product_id' => 1, 'name' => "ETRON"],
            ['product_id' => 1, 'name' => "EULER MOTORS"],
            ['product_id' => 1, 'name' => "EUROPE FORESTRY"],
            ['product_id' => 1, 'name' => "EUSI MOTORS"],
            ['product_id' => 1, 'name' => "EXIDE"],
            ['product_id' => 1, 'name' => "EXTREME MOTORS"],
            ['product_id' => 1, 'name' => "F CHALLENGER"],
            ['product_id' => 1, 'name' => "FARM TRAC"],
            ['product_id' => 1, 'name' => "FEDE INDUSTRIES PVT LTD"],
            ['product_id' => 1, 'name' => "FERRARI"],
            ['product_id' => 1, 'name' => "FIAT"],
            ['product_id' => 1, 'name' => "FINE EQUIPMENTS"],
            ['product_id' => 1, 'name' => "FITWEL"],
            ['product_id' => 1, 'name' => "FORCE"],
            ['product_id' => 1, 'name' => "FORD"],
            ['product_id' => 1, 'name' => "FOTON"],
            ['product_id' => 1, 'name' => "G K RICKSHAW PVT LTD"],
            ['product_id' => 1, 'name' => "GAHIR AGRICULTURAL INDUSTIRES "],
            ['product_id' => 1, 'name' => "GAM"],
            ['product_id' => 1, 'name' => "GANPATI ENTERPRISES"],
            ['product_id' => 1, 'name' => "GAYATRI"],
            ['product_id' => 1, 'name' => "GEM MOTORS"],
            ['product_id' => 1, 'name' => "GENERAL MOTOR"],
            ['product_id' => 1, 'name' => "GILL AGRICULTURE WORKS"],
            ['product_id' => 1, 'name' => "GK RICKSHAW PVT LTD"],
            ['product_id' => 1, 'name' => "GKON"],
            ['product_id' => 1, 'name' => "GLOBAL"],
            ['product_id' => 1, 'name' => "GMMCO LTD"],
            ['product_id' => 1, 'name' => "GODAVARI ELECTRIC MOTORS"],
            ['product_id' => 1, 'name' => "GODREJ"],
            ['product_id' => 1, 'name' => "GOELS ALANI"],
            ['product_id' => 1, 'name' => "GOENKA ELECTRIC MOTOR"],
            ['product_id' => 1, 'name' => "GOLD HOFES"],
            ['product_id' => 1, 'name' => "GOLDSTONE"],
            ['product_id' => 1, 'name' => "GRD MOTORS"],
            ['product_id' => 1, 'name' => "GREAVES COTTON"],
            ['product_id' => 1, 'name' => "GREEN RICK"],
            ['product_id' => 1, 'name' => "GREEN TECHNOLOGIES"],
            ['product_id' => 1, 'name' => "GREENWHEELS AUTOMOBILE PVT LTD"],
            ['product_id' => 1, 'name' => "GROMAX AGRI EQUIPMENT LTD"],
            ['product_id' => 1, 'name' => "GROVE"],
            ['product_id' => 1, 'name' => "HAMM"],
            ['product_id' => 1, 'name' => "HARISON"],
            ['product_id' => 1, 'name' => "HARVESTER"],
            ['product_id' => 1, 'name' => "HAYABUSA"],
            ['product_id' => 1, 'name' => "HAYASA"],
            ['product_id' => 1, 'name' => "HI TECH"],
            ['product_id' => 1, 'name' => "HIM TEKNOFORGE LTD"],
            ['product_id' => 1, 'name' => "HINDUSTAN MOTOR"],
            ['product_id' => 1, 'name' => "HINDUSTAN MOTOR CORPORATION"],
            ['product_id' => 1, 'name' => "HINO"],
            ['product_id' => 1, 'name' => "HIRA AGRO INDUSTRIES"],
            ['product_id' => 1, 'name' => "HITACHI"],
            ['product_id' => 1, 'name' => "HMT"],
            ['product_id' => 1, 'name' => "HONDA"],
            ['product_id' => 1, 'name' => "Hooghly Motors Pvt Ltd"],
            ['product_id' => 1, 'name' => "HOP MOTORS"],
            ['product_id' => 1, 'name' => "HOTAGE CORPORATION"],
            ['product_id' => 1, 'name' => "HUMMER"],
            ['product_id' => 1, 'name' => "HUNDA EV"],
            ['product_id' => 1, 'name' => "HYDRA"],
            ['product_id' => 1, 'name' => "HYUNDAI"],
            ['product_id' => 1, 'name' => "ICML"],
            ['product_id' => 1, 'name' => "ICV"],
            ['product_id' => 1, 'name' => "INDIAN MOTORS"],
            ['product_id' => 1, 'name' => "INDITAL EQUIPMENT"],
            ['product_id' => 1, 'name' => "INDO FARM"],
            ['product_id' => 1, 'name' => "INDO WAGEN"],
            ['product_id' => 1, 'name' => "INGERSOLL RAND"],
            ['product_id' => 1, 'name' => "International Tractors Ltd"],
            ['product_id' => 1, 'name' => "ISUZU"],
            ['product_id' => 1, 'name' => "J S AUTO PVT LTD"],
            ['product_id' => 1, 'name' => "JADHAO AGRO"],
            ['product_id' => 1, 'name' => "JAGUAR"],
            ['product_id' => 1, 'name' => "JAJODIA COMMODITIES PVT LTD"],
            ['product_id' => 1, 'name' => "JANGID MOTORS"],
            ['product_id' => 1, 'name' => "JAY AMBE"],
            ['product_id' => 1, 'name' => "JBM AUTO"],
            ['product_id' => 1, 'name' => "JCB"],
            ['product_id' => 1, 'name' => "JCW"],
            ['product_id' => 1, 'name' => "JEEP"],
            ['product_id' => 1, 'name' => "JEZZA"],
            ['product_id' => 1, 'name' => "JITENDRA TEMPO PARTS"],
            ['product_id' => 1, 'name' => "JOGINDER SATYA"],
            ['product_id' => 1, 'name' => "JOHN DEERE"],
            ['product_id' => 1, 'name' => "JONO CASTING"],
            ['product_id' => 1, 'name' => "JS AUTO PVT LTD"],
            ['product_id' => 1, 'name' => "JS MOBILEON PVT LTD"],
            ['product_id' => 1, 'name' => "JUNGHEINRICH"],
            ['product_id' => 1, 'name' => "KABMAX"],
            ['product_id' => 1, 'name' => "KALMAR"],
            ['product_id' => 1, 'name' => "KALMAR CONTCHAMP"],
            ['product_id' => 1, 'name' => "KAMAZ"],
            ['product_id' => 1, 'name' => "KAPTECH"],
            ['product_id' => 1, 'name' => "KARTAR AGRO INDUSTRIES"],
            ['product_id' => 1, 'name' => "KATO"],
            ['product_id' => 1, 'name' => "KAYEMEL MACHINE PVT LTD"],
            ['product_id' => 1, 'name' => "KC"],
            ['product_id' => 1, 'name' => "KERALA AUTO"],
            ['product_id' => 1, 'name' => "KGN Industries"],
            ['product_id' => 1, 'name' => "KHALSA"],
            ['product_id' => 1, 'name' => "KHALSAE VEHICLES PVT LTD"],
            ['product_id' => 1, 'name' => "KHUSHI"],
            ['product_id' => 1, 'name' => "KIA"],
            ['product_id' => 1, 'name' => "KINETIC GREEN ENERGY"],
            ['product_id' => 1, 'name' => "KION"],
            ['product_id' => 1, 'name' => "KIRTI SOLAR LTD"],
            ['product_id' => 1, 'name' => "KOMAKI"],
            ['product_id' => 1, 'name' => "KOMATSU"],
            ['product_id' => 1, 'name' => "KRANTI AUTOMOBILES LTD"],
            ['product_id' => 1, 'name' => "KRISHAN"],
            ['product_id' => 1, 'name' => "KRISHNA ENGINEERING WORKS"],
            ['product_id' => 1, 'name' => "KRUPP"],
            ['product_id' => 1, 'name' => "KS AGRICULTURAL INDUSTRIES PVT LTD"],
            ['product_id' => 1, 'name' => "KUBOTA"],
            ['product_id' => 1, 'name' => "KUKU AUTOMOTIVES"],
            ['product_id' => 1, 'name' => "KURUKSHETRA"],
            ['product_id' => 1, 'name' => "KYB CONMAT PVT LTD"],
            ['product_id' => 1, 'name' => "L&T"],
            ['product_id' => 1, 'name' => "LAKSHYA"],
            ['product_id' => 1, 'name' => "LAMBORGHINI"],
            ['product_id' => 1, 'name' => "LANCER BOSS"],
            ['product_id' => 1, 'name' => "LAND ROVER"],
            ['product_id' => 1, 'name' => "LAWAT MOTORS"],
            ['product_id' => 1, 'name' => "LECTRIX"],
            ['product_id' => 1, 'name' => "LEEBOY"],
            ['product_id' => 1, 'name' => "LEORIDE"],
            ['product_id' => 1, 'name' => "LEXUS"],
            ['product_id' => 1, 'name' => "LIEBHERR"],
            ['product_id' => 1, 'name' => "LINCOLN"],
            ['product_id' => 1, 'name' => "LIUGONG"],
            ['product_id' => 1, 'name' => "LOADER"],
            ['product_id' => 1, 'name' => "LOHIA"],
            ['product_id' => 1, 'name' => "LOTIA MOTORS LTD"],
            ['product_id' => 1, 'name' => "MAA SHAKTI EXIM"],
            ['product_id' => 1, 'name' => "MAC AUTO INDIA"],
            ['product_id' => 1, 'name' => "MACONS EQUIPMENTS PVT LTD"],
            ['product_id' => 1, 'name' => "MAHABAL"],
            ['product_id' => 1, 'name' => "MAHINDRA & MAHINDRA"],
            ['product_id' => 1, 'name' => "MALAK TECHNO PVT LTD"],
            ['product_id' => 1, 'name' => "MALKIT"],
            ['product_id' => 1, 'name' => "MAN"],
            ['product_id' => 1, 'name' => "MANISH EV INTERNATIONAL"],
            ['product_id' => 1, 'name' => "MANITA CITY MOTORS LLP"],
            ['product_id' => 1, 'name' => "MANITOU EQUIPMENT INDIA PVT LTD"],
            ['product_id' => 1, 'name' => "MARUTI"],
            ['product_id' => 1, 'name' => "MASERATI"],
            ['product_id' => 1, 'name' => "MASSEY FERGUSON"],
            ['product_id' => 1, 'name' => "MAXCON"],
            ['product_id' => 1, 'name' => "MAYURI SAERA ELECTRIC AUTO"],
            ['product_id' => 1, 'name' => "MAZDA"],
            ['product_id' => 1, 'name' => "MCLAREN"],
            ['product_id' => 1, 'name' => "MEC LIFT"],
            ['product_id' => 1, 'name' => "MERCEDES-BENZ"],
            ['product_id' => 1, 'name' => "MILYF"],
            ['product_id' => 1, 'name' => "MINI"],
            ['product_id' => 1, 'name' => "MINI METRO"],
            ['product_id' => 1, 'name' => "MITSUBISHI"],
            ['product_id' => 1, 'name' => "MLR AUTO PVT LTD"],
            ['product_id' => 1, 'name' => "MOBILE"],
            ['product_id' => 1, 'name' => "MODIFIED CARS"],
            ['product_id' => 1, 'name' => "MODIFIED VEHICLE"],
            ['product_id' => 1, 'name' => "MORRIS GARAGES"],
            ['product_id' => 1, 'name' => "MOVE STONE"],
            ['product_id' => 1, 'name' => "MTANDT"],
            ['product_id' => 1, 'name' => "NAIK TROLLEY"],
            ['product_id' => 1, 'name' => "NANDI"],
            ['product_id' => 1, 'name' => "NDS ECO MOTORS"],
            ['product_id' => 1, 'name' => "NEEDLE EYE"],
            ['product_id' => 1, 'name' => "NEW ARENA INDIA"],
            ['product_id' => 1, 'name' => "NEW HOLLAND"],
            ['product_id' => 1, 'name' => "NEW HOLLAND FIAT INDIA PRIVATE LTD"],
            ['product_id' => 1, 'name' => "NHD SUPER"],
            ['product_id' => 1, 'name' => "NIPUN SANYANTRA PVT LTD"],
            ['product_id' => 1, 'name' => "NISSAN"],
            ['product_id' => 1, 'name' => "NOVA"],
            ['product_id' => 1, 'name' => "NRJ ELECTRIC MOTOR"],
            ['product_id' => 1, 'name' => "OGATA MOTORS"],
            ['product_id' => 1, 'name' => "OLECTRA"],
            ['product_id' => 1, 'name' => "OM BALAJEE AUTOMOBILE"],
            ['product_id' => 1, 'name' => "OM INDUSTRIES"],
            ['product_id' => 1, 'name' => "OM RAJ AUTOTECH LLP"],
            ['product_id' => 1, 'name' => "OMEGA"],
            ['product_id' => 1, 'name' => "OMEGA SEIKI MOBILITY"],
            ['product_id' => 1, 'name' => "OPEL"],
            ['product_id' => 1, 'name' => "PACE AGRO PVT LTD"],
            ['product_id' => 1, 'name' => "PAL"],
            ['product_id' => 1, 'name' => "PANTHER ELECTRIC"],
            ['product_id' => 1, 'name' => "PARAS INDUSTRIES"],
            ['product_id' => 1, 'name' => "PARI MOTORS"],
            ['product_id' => 1, 'name' => "PASHUPATI VEHICLES PVT LTD"],
            ['product_id' => 1, 'name' => "PATS MOTOR CORP"],
            ['product_id' => 1, 'name' => "PERFECT AUTO"],
            ['product_id' => 1, 'name' => "PHOENIX"],
            ['product_id' => 1, 'name' => "PIAGGIO"],
            ['product_id' => 1, 'name' => "PLAUDIT"],
            ['product_id' => 1, 'name' => "PMI ELECTRO MOBILITY"],
            ['product_id' => 1, 'name' => "POOSHPAK AUTOMOBILE PVT LTD"],
            ['product_id' => 1, 'name' => "PORSCHE"],
            ['product_id' => 1, 'name' => "POWERTRAC"],
            ['product_id' => 1, 'name' => "PRAG MOTORS"],
            ['product_id' => 1, 'name' => "PRAKASH ENTERPRISES"],
            ['product_id' => 1, 'name' => "PRAMUKH"],
            ['product_id' => 1, 'name' => "PREET"],
            ['product_id' => 1, 'name' => "PREMIER"],
            ['product_id' => 1, 'name' => "PREMIER AUTOMOBILES"],
            ['product_id' => 1, 'name' => "PRIDE E MOTORS"],
            ['product_id' => 1, 'name' => "PUBANG"],
            ['product_id' => 1, 'name' => "PUNJAB TRACTORS LIMITED"],
            ['product_id' => 1, 'name' => "PUTZMEISTER"],
            ['product_id' => 1, 'name' => "RAHUL"],
            ['product_id' => 1, 'name' => "RAJ"],
            ['product_id' => 1, 'name' => "RAJESH STEEL"],
            ['product_id' => 1, 'name' => "RAJIV RAJ VEHICLE"],
            ['product_id' => 1, 'name' => "RAM"],
            ['product_id' => 1, 'name' => "RASANDIK"],
            ['product_id' => 1, 'name' => "RCJ"],
            ['product_id' => 1, 'name' => "REAYA"],
            ['product_id' => 1, 'name' => "REEP"],
            ['product_id' => 1, 'name' => "REFLEX CONTROL"],
            ['product_id' => 1, 'name' => "RENAULT"],
            ['product_id' => 1, 'name' => "REVA"],
            ['product_id' => 1, 'name' => "ROANSOME MOTORS"],
            ['product_id' => 1, 'name' => "ROKET ELECTRIC VEHICLE"],
            ['product_id' => 1, 'name' => "ROLLS ROYCE"],
            ['product_id' => 1, 'name' => "RUTBA PRODUCTS PVT LTD"],
            ['product_id' => 1, 'name' => "SAARTHI"],
            ['product_id' => 1, 'name' => "SAERA ELECTRIC AUTO PVT LTD"],
            ['product_id' => 1, 'name' => "SAHEJ"],
            ['product_id' => 1, 'name' => "SAHNIANAND E VEHICLES PVT LTD"],
            ['product_id' => 1, 'name' => "SAKSHAM"],
            ['product_id' => 1, 'name' => "SAME"],
            ['product_id' => 1, 'name' => "SAN MOTORS"],
            ['product_id' => 1, 'name' => "SANY"],
            ['product_id' => 1, 'name' => "SATHI MOTORS"],
            ['product_id' => 1, 'name' => "SCANIA"],
            ['product_id' => 1, 'name' => "SCHEUERLE FAHRZEUGFABRIK"],
            ['product_id' => 1, 'name' => "SCHWING STETTER"],
            ['product_id' => 1, 'name' => "SCOOTER INDIA LTD"],
            ['product_id' => 1, 'name' => "SDLG"],
            ['product_id' => 1, 'name' => "SEC RJMT ENGINEERING PVT LTD"],
            ['product_id' => 1, 'name' => "SHAKTI AUTO"],
            ['product_id' => 1, 'name' => "SHAKTIMAN"],
            ['product_id' => 1, 'name' => "SHAKTTI CONSTRUCTIONS EQUIPMENT PRIVATE LIMITED"],
            ['product_id' => 1, 'name' => "SHIGAN EVOLTZ LTD"],
            ['product_id' => 1, 'name' => "SHIV OM INDIA"],
            ['product_id' => 1, 'name' => "SHREE SHYAM DIESELS"],
            ['product_id' => 1, 'name' => "SHRI BARSANA E-VEHCILES PVT LTD"],
            ['product_id' => 1, 'name' => "SHRI NAMO ELECTRIC"],
            ['product_id' => 1, 'name' => "SHRI RAM"],
            ['product_id' => 1, 'name' => "SHRIJI ENGINEERING WORKS"],
            ['product_id' => 1, 'name' => "SHRIRAJ ELECTRIC VEHICLES"],
            ['product_id' => 1, 'name' => "SINGH AUTOMOBILES"],
            ['product_id' => 1, 'name' => "SINGHAL ENTERPRISES"],
            ['product_id' => 1, 'name' => "SINGHAM AUTO"],
            ['product_id' => 1, 'name' => "SITARA"],
            ['product_id' => 1, 'name' => "SIX SENSES AUTO"],
            ['product_id' => 1, 'name' => "SKODA"],
            ['product_id' => 1, 'name' => "SKS TRADE INDIA PVT LTD"],
            ['product_id' => 1, 'name' => "SKYRIDE"],
            ['product_id' => 1, 'name' => "SMITH MOTORS"],
            ['product_id' => 1, 'name' => "SML ISUZU"],
            ['product_id' => 1, 'name' => "SODYCO"],
            ['product_id' => 1, 'name' => "SOLIS"],
            ['product_id' => 1, 'name' => "SONALIKA"],
            ['product_id' => 1, 'name' => "SOODA"],
            ['product_id' => 1, 'name' => "SOORAJ AUTOMOBILES LTD"],
            ['product_id' => 1, 'name' => "SPEEGO"],
            ['product_id' => 1, 'name' => "SRD RENEWABLES"],
            ['product_id' => 1, 'name' => "SSANGYONG"],
            ['product_id' => 1, 'name' => "SSB INDUSTRIES"],
            ['product_id' => 1, 'name' => "SSEV ENTERPRISES PVT LTD"],
            ['product_id' => 1, 'name' => "STANDARD COMBINES PVT LTD"],
            ['product_id' => 1, 'name' => "STANDARD CORPORATION INDIA LTD "],
            ['product_id' => 1, 'name' => "STAR"],
            ['product_id' => 1, 'name' => "STAR IGLOBAL AUTOMOTIVE PVT LTD"],
            ['product_id' => 1, 'name' => "SUGANJI RARA ELECTRICAL VEHICLE PVT LTD"],
            ['product_id' => 1, 'name' => "SUMFONL"],
            ['product_id' => 1, 'name' => "SUNARIYA MOTORS PVT LTD"],
            ['product_id' => 1, 'name' => "SUNSET TRADE PVT LTD"],
            ['product_id' => 1, 'name' => "SUPER ECO"],
            ['product_id' => 1, 'name' => "SUPER METRO"],
            ['product_id' => 1, 'name' => "SUPER POWER MOTORS"],
            ['product_id' => 1, 'name' => "SUPER TECH"],
            ['product_id' => 1, 'name' => "Supreme Smart Power Pvt Ltd"],
            ['product_id' => 1, 'name' => "SUPRO TRAILER"],
            ['product_id' => 1, 'name' => "SUZUKI"],
            ['product_id' => 1, 'name' => "SWARAJ"],
            ['product_id' => 1, 'name' => "SYNDICATE AUTO"],
            ['product_id' => 1, 'name' => "TADANO FAUN"],
            ['product_id' => 1, 'name' => "TAFE"],
            ['product_id' => 1, 'name' => "TATA"],
            ['product_id' => 1, 'name' => "TAURUS"],
            ['product_id' => 1, 'name' => "TDV"],
            ['product_id' => 1, 'name' => "TEJA"],
            ['product_id' => 1, 'name' => "TEJAS GREEN"],
            ['product_id' => 1, 'name' => "TELCON"],
            ['product_id' => 1, 'name' => "TELSA"],
            ['product_id' => 1, 'name' => "TEMPO"],
            ['product_id' => 1, 'name' => "TEREX"],
            ['product_id' => 1, 'name' => "TEREX VECTRA"],
            ['product_id' => 1, 'name' => "TERRA MOTORS"],
            ['product_id' => 1, 'name' => "TESLA"],
            ['product_id' => 1, 'name' => "THUKRAL ELECTRIC"],
            ['product_id' => 1, 'name' => "TI CLEAN MOBILITY PVT LTD"],
            ['product_id' => 1, 'name' => "TIL LTD"],
            ['product_id' => 1, 'name' => "TOMAX"],
            ['product_id' => 1, 'name' => "TOP TEAM MACHINES PVT LTD"],
            ['product_id' => 1, 'name' => "TOYOTA"],
            ['product_id' => 1, 'name' => "TPS"],
            ['product_id' => 1, 'name' => "TRAILER"],
            ['product_id' => 1, 'name' => "TRINITY ELECTRIC"],
            ['product_id' => 1, 'name' => "TRISHIKA INDUSTRIES"],
            ['product_id' => 1, 'name' => "TRISHUL"],
            ['product_id' => 1, 'name' => "TRIUMPH"],
            ['product_id' => 1, 'name' => "TSM"],
            ['product_id' => 1, 'name' => "TUK INDUSTRY"],
            ['product_id' => 1, 'name' => "TVS"],
            ['product_id' => 1, 'name' => "TWINKLE TRADECOM PVT LTD"],
            ['product_id' => 1, 'name' => "TWO FRIENDS AUTO ELECTRIC CO"],
            ['product_id' => 1, 'name' => "U P TELELINKS LTD"],
            ['product_id' => 1, 'name' => "UDAAN"],
            ['product_id' => 1, 'name' => "UNIPAV"],
            ['product_id' => 1, 'name' => "UNIQUE ENTERPRISES"],
            ['product_id' => 1, 'name' => "UNIVERSAL"],
            ['product_id' => 1, 'name' => "URBANIA"],
            ['product_id' => 1, 'name' => "UTTAM CONSTRUCTION EQUIPMENT"],
            ['product_id' => 1, 'name' => "VAIBHAV AUTO"],
            ['product_id' => 1, 'name' => "VANDE BHARAT ELECTRIC VEHICLE"],
            ['product_id' => 1, 'name' => "VANI"],
            ['product_id' => 1, 'name' => "VE COMMERCIAL VEHICLES LTD"],
            ['product_id' => 1, 'name' => "VEECTERO E VEHICLES"],
            ['product_id' => 1, 'name' => "VICTORY ELECTRIC INTERNATIONAL"],
            ['product_id' => 1, 'name' => "VIDA"],
            ['product_id' => 1, 'name' => "VIJAYS COOLMAX PVT LTD"],
            ['product_id' => 1, 'name' => "VIJAYSHREE AUTOCOM LIMITED"],
            ['product_id' => 1, 'name' => "VIKRAM"],
            ['product_id' => 1, 'name' => "VIMAL UNIVERSAL TRADE PVT LTD"],
            ['product_id' => 1, 'name' => "VIPUL"],
            ['product_id' => 1, 'name' => "VISHAL"],
            ['product_id' => 1, 'name' => "VISHVAKARMA"],
            ['product_id' => 1, 'name' => "VMT"],
            ['product_id' => 1, 'name' => "VOLKSWAGEN"],
            ['product_id' => 1, 'name' => "VOLTAS"],
            ['product_id' => 1, 'name' => "VOLVO"],
            ['product_id' => 1, 'name' => "VRINDA ENTERPRISES"],
            ['product_id' => 1, 'name' => "VST TILLERS TRACTORS LTD"],
            ['product_id' => 1, 'name' => "WIRTGEN INDIA"],
            ['product_id' => 1, 'name' => "XCMG"],
            ['product_id' => 1, 'name' => "XXPLORE"],
            ['product_id' => 1, 'name' => "YANMAR"],
            ['product_id' => 1, 'name' => "YATRI"],
            ['product_id' => 1, 'name' => "YC ELECTRIC VEHICLE"],
            ['product_id' => 1, 'name' => "ZENIAK INNOVATION"],
            ['product_id' => 1, 'name' => "ZEOPLUS"],
            ['product_id' => 1, 'name' => "ZOOMLION HEAVY INDUSTRY CO LTD"],
            ['product_id' => 2, 'name' => "ADMS"],
            ['product_id' => 2, 'name' => "AMO ELECTRIC"],
            ['product_id' => 2, 'name' => "AMPERE"],
            ['product_id' => 2, 'name' => "APRILIA"],
            ['product_id' => 2, 'name' => "ARROW"],
            ['product_id' => 2, 'name' => "ATHER"],
            ['product_id' => 2, 'name' => "AVERA"],
            ['product_id' => 2, 'name' => "Ayaan Electronics Private Limited"],
            ['product_id' => 2, 'name' => "BAJAJ"],
            ['product_id' => 2, 'name' => "BATTRE"],
            ['product_id' => 2, 'name' => "BENELLI"],
            ['product_id' => 2, 'name' => "BENLING"],
            ['product_id' => 2, 'name' => "BEST EVM"],
            ['product_id' => 2, 'name' => "BGAUSS"],
            ['product_id' => 2, 'name' => "BMW"],
            ['product_id' => 2, 'name' => "BNC MOTORS"],
            ['product_id' => 2, 'name' => "BOUNCE"],
            ['product_id' => 2, 'name' => "CLASSIC LEGENDS PVT LTD"],
            ['product_id' => 2, 'name' => "COSBIKE"],
            ['product_id' => 2, 'name' => "DEJA VU"],
            ['product_id' => 2, 'name' => "DSK MOTOWHEELS"],
            ['product_id' => 2, 'name' => "DUCATI"],
            ['product_id' => 2, 'name' => "DYNAMO"],
            ['product_id' => 2, 'name' => "E-ASHWA"],
            ['product_id' => 2, 'name' => "ELECTROTHERM"],
            ['product_id' => 2, 'name' => "ELTHOR ENERGY PVT LTD"],
            ['product_id' => 2, 'name' => "EVEX INDIA"],
            ['product_id' => 2, 'name' => "EVTRIC MOTORS"],
            ['product_id' => 2, 'name' => "EXIDE NEO"],
            ['product_id' => 2, 'name' => "EZYRIDE"],
            ['product_id' => 2, 'name' => "FB Mondial"],
            ['product_id' => 2, 'name' => "FERRANZA"],
            ['product_id' => 2, 'name' => "FIDATO"],
            ['product_id' => 2, 'name' => "FLYCON MOTORS"],
            ['product_id' => 2, 'name' => "GANPATI ENTERPRISES"],
            ['product_id' => 2, 'name' => "GAURA ELECTRIC"],
            ['product_id' => 2, 'name' => "GEMOPAI"],
            ['product_id' => 2, 'name' => "GODAWARI ELECTRIC MOTORS"],
            ['product_id' => 2, 'name' => "GREEN VALLEY MOTORS"],
            ['product_id' => 2, 'name' => "GT FORCE"],
            ['product_id' => 2, 'name' => "HARLEY DAVIDSON"],
            ['product_id' => 2, 'name' => "HERO"],
            ['product_id' => 2, 'name' => "HERO ELECTRIC"],
            ['product_id' => 2, 'name' => "HERO HONDA"],
            ['product_id' => 2, 'name' => "HILMAN"],
            ['product_id' => 2, 'name' => "HONDA"],
            ['product_id' => 2, 'name' => "HOP ELECTRIC"],
            ['product_id' => 2, 'name' => "HUSQVARNA"],
            ['product_id' => 2, 'name' => "HYOSUNG"],
            ['product_id' => 2, 'name' => "INDIAN MOTORCYCLE"],
            ['product_id' => 2, 'name' => "IVOOMI"],
            ['product_id' => 2, 'name' => "JAWA"],
            ['product_id' => 2, 'name' => "JITENDRA NEW EV TECH PVT LTD"],
            ['product_id' => 2, 'name' => "JIVA"],
            ['product_id' => 2, 'name' => "JOY E-BIKE"],
            ['product_id' => 2, 'name' => "KABIRA MOBILITY"],
            ['product_id' => 2, 'name' => "KAWASAKI"],
            ['product_id' => 2, 'name' => "KEEWAY"],
            ['product_id' => 2, 'name' => "KETRON"],
            ['product_id' => 2, 'name' => "KINETIC"],
            ['product_id' => 2, 'name' => "KINETIC GREEN ENERGY"],
            ['product_id' => 2, 'name' => "KOMAKI"],
            ['product_id' => 2, 'name' => "KTM"],
            ['product_id' => 2, 'name' => "KYTE"],
            ['product_id' => 2, 'name' => "LECTRIX EV PVT LTD"],
            ['product_id' => 2, 'name' => "LEO ELECTRIC"],
            ['product_id' => 2, 'name' => "lI-IONS ELEKTRIK SOLUTIONS"],
            ['product_id' => 2, 'name' => "LML"],
            ['product_id' => 2, 'name' => "M2GO ELECTRIC"],
            ['product_id' => 2, 'name' => "MAHINDRA & MAHINDRA"],
            ['product_id' => 2, 'name' => "MANTRA"],
            ['product_id' => 2, 'name' => "MOTIONMAN"],
            ['product_id' => 2, 'name' => "MOTO GUZZI"],
            ['product_id' => 2, 'name' => "MOTO MORINI"],
            ['product_id' => 2, 'name' => "MOTO VAULT"],
            ['product_id' => 2, 'name' => "MV AGUSTA"],
            ['product_id' => 2, 'name' => "NEXZU"],
            ['product_id' => 2, 'name' => "ODYSSE"],
            ['product_id' => 2, 'name' => "OKAYA"],
            ['product_id' => 2, 'name' => "OKINAWA"],
            ['product_id' => 2, 'name' => "OLA"],
            ['product_id' => 2, 'name' => "OLOO"],
            ['product_id' => 2, 'name' => "ONE ELECTRIC"],
            ['product_id' => 2, 'name' => "OREVA"],
            ['product_id' => 2, 'name' => "OZOTEC AUTOMOBILE PVT LTD"],
            ['product_id' => 2, 'name' => "PIAGGIO"],
            ['product_id' => 2, 'name' => "PRAISE"],
            ['product_id' => 2, 'name' => "PURE EV"],
            ['product_id' => 2, 'name' => "QJ MOTOR"],
            ['product_id' => 2, 'name' => "QUANTUM"],
            ['product_id' => 2, 'name' => "REMARK"],
            ['product_id' => 2, 'name' => "REVOLT"],
            ['product_id' => 2, 'name' => "RIVER"],
            ['product_id' => 2, 'name' => "ROWWET"],
            ['product_id' => 2, 'name' => "ROYAL ENFIELD"],
            ['product_id' => 2, 'name' => "SAMRATH"],
            ['product_id' => 2, 'name' => "SARTHAK"],
            ['product_id' => 2, 'name' => "SILVELINE"],
            ['product_id' => 2, 'name' => "SILVELINE"],
            ['product_id' => 2, 'name' => "Sokudo"],
            ['product_id' => 2, 'name' => "SUZUKI"],
            ['product_id' => 2, 'name' => "SWM"],
            ['product_id' => 2, 'name' => "TNR"],
            ['product_id' => 2, 'name' => "TORK"],
            ['product_id' => 2, 'name' => "TOXMO"],
            ['product_id' => 2, 'name' => "TRIUMPH"],
            ['product_id' => 2, 'name' => "TUNWAL"],
            ['product_id' => 2, 'name' => "TVS"],
            ['product_id' => 2, 'name' => "UJAAS"],
            ['product_id' => 2, 'name' => "UM"],
            ['product_id' => 2, 'name' => "UNITED MOTORS"],
            ['product_id' => 2, 'name' => "UNKNOWN"],
            ['product_id' => 2, 'name' => "VEGH"],
            ['product_id' => 2, 'name' => "VESPA"],
            ['product_id' => 2, 'name' => "VIBGYOR"],
            ['product_id' => 2, 'name' => "Warivo Motor India Private Limited"],
            ['product_id' => 2, 'name' => "WHITE CARBON"],
            ['product_id' => 2, 'name' => "WROLEY"],
            ['product_id' => 2, 'name' => "YAKUZA"],
            ['product_id' => 2, 'name' => "YAMAHA"],
            ['product_id' => 2, 'name' => "YEZDI"],
            ['product_id' => 2, 'name' => "YO BIKES"],
            ['product_id' => 2, 'name' => "ZELIO"],
            ['product_id' => 2, 'name' => "ZONTES"],
        ];

        Make::truncate();
        foreach ($makes as $make) {
            Make::create([
                'product_id' => $make['product_id'],
                'name' => $make['name'],
                'is_active' => true,
            ]);
        }
    }
}
